### ISSUE TITLE
problems loading nvidia-uvm

### ISSUE THREAD

**Issue by nlooije** [Bumblebee-Project/Bumblebee#623] opened 2014-12-18 19:01 UTC
On a fresh system with the following specs:
ubuntu gnome 14.04.1
3.13.0-43-generic
nvidia-331-updates (GTX 765m)

When trying to run (py)cuda applications on a fresh install, I get an error:
>pycuda._driver.Error: cuInit failed: unknown

Apparently the uvm module is not loaded as installing nvidia-modprobe shows the additional error:
> modprobe: FATAL: Module nvidia-uvm not found.

However, the nvidia-331-updates-uvm module is installed but apparantly not used and also issuing:
> sudo modprobe nvidia-331-updates-uvm

gives:
> modprobe: ERROR: could not insert 'nvidia_331_updates_uvm': No such device

However, editing /etc/modprobe.d/bumblebee.conf with:
> alias nvidia-uvm nvidia-331-updates-uvm

allows to run the (py)cuda applications. But the discrete gpu remains on:
> cat /proc/acpi/bbswitch -> 0000:01:00.0 ON

dmesg:
> [ 3792.948204] bbswitch: enabling discrete graphics
> [ 3793.421339] [drm] Initialized nvidia-drm 0.0.0 20130102 for 0000:01:00.0 on minor 1
> [ 3793.421343] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  331.113  Mon Dec  1 21:08:13 PST 2014
> [ 3793.436864] vgaarb: this pci device is not a vga device
> [ 3793.437342] nvidia 0000:01:00.0: irq 50 for MSI/MSI-X
> [ 3793.962565] vgaarb: this pci device is not a vga device
> [ 3794.409463] nvidia_uvm: Loaded the UVM driver, major device number 251
> [ 3806.836508] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20131115/nsarguments-95)

How do I deal with this uvm issue?

**Comment by ArchangeGabriel** [comment] 2015-01-01 22:14
Ok, I think it’s a duplicate of #604. We will continue there.

**Closed by ArchangeGabriel** 2015-01-01 22:14 UTC

**Comment by samarth-robo** [comment] 2015-09-20 16:16
Was this solved? It seems like the issue is to provide the same alias to the unloading mechanism, but I don't know how to do that.

**Comment by ArchangeGabriel** [comment] 2015-12-27 21:42
It’s going to be solved soon, we’re working on aliases handling.
