### ISSUE TITLE
turning on/off graphic card

### ISSUE THREAD

**Issue by Seikitsu** [Bumblebee-Project/Bumblebee#729] opened 2016-01-12 15:05 UTC
Hello! Has there been any conclusion of https://github.com/Bumblebee-Project/Bumblebee/issues/719 ? I basically have same problem, using GPU can quicky cause overheating of my CPU and when it's switched ON it doesn't automatically turn off and I cant turn it off either, unless I use this "sudo rmmod nvidia_modeset nvidia && sudo tee /proc/acpi/bbswitch <<<OFF" which doesnt really work anyway because a) I would like it to be automatic b) it immediately turns back ON

**Comment by HileV** [comment] 2016-02-26 00:26
I have same issue. Help ppl! I wanna it to be automatic!

**Comment by FadeMind** [comment] 2016-02-26 07:54
@Seikitsu @HileV grab sources with hard workaround patches. This is for Arch Linux but patchset can be easy implemented in other distros: 
[bumblebee-3.2.1-11.src.tar.gz](https://github.com/Bumblebee-Project/Bumblebee/files/147809/bumblebee-3.2.1-11.src.tar.gz)

**Comment by HileV** [comment] 2016-02-26 10:49
@FadeMind, how to install it?

**Comment by HileV** [comment] 2016-02-26 10:54
@FadeMind, THANK YOU BRO!!!

**Comment by ArchangeGabriel** [comment] 2016-05-06 11:18
Closing this as dupe of #719.

**Closed by ArchangeGabriel** 2016-05-06 11:18 UTC
