### ISSUE TITLE
Debian sid [ERROR]Cannot access secondary GPU - error: Could not load GPU driver   

### ISSUE THREAD

**Issue by FateRover** [Bumblebee-Project/Bumblebee#926] opened 2017-12-04 05:48 UTC
Debian sid  kernel 4.13.0 amd64  gtx1060
my latpod goes well with debian stretch kernel 4.9.0.4 and bumblebee ,but when i update kernel to 4.13 and update bumblebee , maybe also update xorg ,then test is it right,

 ~$ optirun glxgears -info
[ 1127.727613] [ERROR]Cannot access secondary GPU - error: Could not load GPU driver

[ 1127.727678] [ERROR]Aborting because fallback start is disabled.
 
________________________________________________________________________

some info 
 ~$ sudo systemctl status bumblebeed
● bumblebeed.service - Bumblebee C Daemon
   Loaded: loaded (/lib/systemd/system/bumblebeed.service; enabled; vendor prese
t: enabled)
   Active: active (running) since Mon 2017-12-04 13:27:57 CST; 2min 3
6s ago
 Main PID: 744 (bumblebeed)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/bumblebeed.service
           └─744 /usr/sbin/bumblebeed
___________________________________________________________________

 ~$ sudo dkms status
bbswitch, 0.8, 4.14.0-1-amd64, x86_64: installed
nvidia-current, 384.98: added
___________________________________________________________________

**Comment by FateRover** [comment] 2017-12-04 05:56
have read   
https://github.com/Bumblebee-Project/Bumblebee/issues/749  
https://github.com/Bumblebee-Project/Bumblebee/issues/834
bumblebee followed:
# Configuration file for Bumblebee. Values should **not** be put between quotes

## Server options. Any change made in this section will need a server restart
# to take effect.
[bumblebeed]
# The secondary Xorg server DISPLAY number
VirtualDisplay=:8
# Should the unused Xorg server be kept running? Set this to true if waiting
# for X to be ready is too long and don't need power management at all.
KeepUnusedXServer=false
# The name of the Bumbleblee server group name (GID name)
ServerGroup=bumblebee
# Card power state at exit. Set to false if the card shoud be ON when Bumblebee
# server exits.
TurnCardOffAtExit=false
# The default behavior of '-f' option on optirun. If set to "true", '-f' will
# be ignored.
NoEcoModeOverride=false
# The Driver used by Bumblebee server. If this value is not set (or empty),
# auto-detection is performed. The available drivers are nvidia and nouveau
# (See also the driver-specific sections below)
Driver=nvidia
# Directory with a dummy config file to pass as a -configdir to secondary X
XorgConfDir=/etc/bumblebee/xorg.conf.d
# Xorg binary to run
XorgBinary=/usr/lib/xorg/Xorg

## Client options. Will take effect on the next optirun executed.
[optirun]
# Acceleration/ rendering bridge, possible values are auto, virtualgl and
# primus.
Bridge=auto
# The method used for VirtualGL to transport frames between X servers.
# Possible values are proxy, jpeg, rgb, xv and yuv.
VGLTransport=proxy
# List of paths which are searched for the primus libGL.so.1 when using
# the primus bridge
PrimusLibraryPath=/usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus:/usr/lib/primus:/usr/lib32/primus
# Should the program run under optirun even if Bumblebee server or nvidia card
# is not available?
AllowFallbackToIGC=false


# Driver-specific settings are grouped under [driver-NAME]. The sections are
# parsed if the Driver setting in [bumblebeed] is set to NAME (or if auto-
# detection resolves to NAME).
# PMMethod: method to use for saving power by disabling the nvidia card, valid
# values are: auto - automatically detect which PM method to use
#         bbswitch - new in BB 3, recommended if available
#       switcheroo - vga_switcheroo method, use at your own risk
#             none - disable PM completely
# https://github.com/Bumblebee-Project/Bumblebee/wiki/Comparison-of-PM-methods

## Section with nvidia driver specific options, only parsed if Driver=nvidia
[driver-nvidia]
# Module name to load, defaults to Driver if empty or unset
KernelDriver=nvidia-384.98
PMMethod=auto
# colon-separated path to the nvidia libraries
LibraryPath=/usr/lib/x86_64-linux-gnu/nvidia:/usr/lib/i386-linux-gnu/nvidia:/usr/lib/nvidia
# comma-separated path of the directory containing nvidia_drv.so and the
# default Xorg modules path
XorgModulePath=/usr/lib/nvidia/nvidia,/usr/lib/xorg/modules
XorgConfFile=/etc/bumblebee/xorg.conf.nvidia

## Section with nouveau driver specific options, only parsed if Driver=nouveau
[driver-nouveau]
KernelDriver=nouveau
PMMethod=auto
XorgConfFile=/etc/bumblebee/xorg.conf.nouveau

**Comment by FateRover** [comment] 2017-12-04 05:57
https://github.com/Bumblebee-Project/Bumblebee/issues/834
https://askubuntu.com/questions/863696/bumblebee-errorcannot-access-secondary-gpu-error-xorg-ee

have read above

**Comment by bluca** [comment] 2017-12-04 10:53
Have a look at:
https://github.com/Bumblebee-Project/Bumblebee/issues/764

There are may more combinations of "acpi_osi", depending on the laptop users are reporting success with different ones. Try to see if there's one that works for you.

**Comment by FateRover** [comment] 2017-12-04 18:40
ii think it isnt acpi issue.because i have found a workaround for old version bumblebee by adding  acpi_osi=！ acpi_osi=“Windows 2009”

**Comment by bluca** [comment] 2017-12-04 19:09
Many people are reporting issues when moving to kernels > 4.10 that can be worked around with the acpi overrides, that's why I suggested it

But actually:

> ~$ sudo dkms status
bbswitch, 0.8, 4.14.0-1-amd64, x86_64: installed
nvidia-current, 384.98: added

That's the problem, you haven't built the modules for the proprietary drivers for your new kernel, do it with:

```sudo dkms install nvidia-current/384.98 -k 4.14.0-1-amd64/x86_64```

**Comment by FateRover** [comment] 2017-12-05 06:01
sorry for that i'm not english native, your mean i should try new "acpi"  line such as acpi_osi='!windows 2015'  or others to see which one works?
_____________________________________________________________________________________
after your commands 
primus: fatal: failed to load any of the libraries: /usr/lib/x86_64-linux-gnu/nvidia/libGL.so.1:/usr/lib/i386-linux-gnu/nvidia/libGL.so.1:/usr/lib/nvidia/libGL.so.1

search for this and,follow this
https://wiki.debian-fr.xyz/NVidia_Optimus_Bumblebee#libGL.so.1
but libgl1-nvidia-glx:i386 isnt in debian sid package , then i solve it by this
https://groups.google.com/forum/#!topic/linux.debian.bugs.dist/kL6mMeGS1kA
luca is bluca ?

mabe should update the dependencies of new bumblebee 
thank you

**Comment by bluca** [comment] 2017-12-05 09:21
Yes that's me - You installed everything and only via packages, right? And it's all up to date? What's the output of:
dpkg -l | grep 384.98

**Comment by FateRover** [comment] 2017-12-05 14:53
```
ii  libegl-nvidia0:amd64                 384.98-3                     amd64        NVIDIA binary EGL library
ii  libgl1-nvidia-glvnd-glx:amd64        384.98-3                     amd64        NVIDIA binary OpenGL/GLX library (GLVND variant)
ii  libgles-nvidia1:amd64                384.98-3                     amd64        NVIDIA binary OpenGL|ES 1.x library
ii  libgles-nvidia2:amd64                384.98-3                     amd64        NVIDIA binary OpenGL|ES 2.x library
ii  libgles1-glvnd-nvidia:amd64          384.98-3                     amd64        NVIDIA binary OpenGL|ES 1.x GLVND stub library
ii  libglx-nvidia0:amd64                 384.98-3                     amd64        NVIDIA binary GLX library
ii  libnvidia-cfg1:amd64                 384.98-3                     amd64        NVIDIA binary OpenGL/GLX configuration library
ii  libnvidia-egl-wayland1:amd64         384.98-3                     amd64        NVIDIA binary Wayland EGL external platform library
ii  libnvidia-eglcore:amd64              384.98-3                     amd64        NVIDIA binary EGL core libraries
ii  libnvidia-glcore:amd64               384.98-3                     amd64        NVIDIA binary OpenGL/GLX core libraries
ii  libnvidia-ml1:amd64                  384.98-3                     amd64        NVIDIA Management Library (NVML) runtime library
ii  libxnvctrl0:amd64                    384.98-1                     amd64        NV-CONTROL X extension (runtime library)
ii  nvidia-alternative                   384.98-3                     amd64        allows the selection of NVIDIA as GLX provider
ii  nvidia-driver                        384.98-3                     amd64        NVIDIA metapackage
ii  nvidia-driver-bin                    384.98-3                     amd64        NVIDIA driver support binaries
ii  nvidia-driver-libs:amd64             384.98-3                     amd64        NVIDIA metapackage (OpenGL/GLX/EGL/GLES libraries)
ii  nvidia-egl-common                    384.98-3                     amd64        NVIDIA binary EGL driver - common files
ii  nvidia-egl-icd:amd64                 384.98-3                     amd64        NVIDIA EGL installable client driver (ICD)
ii  nvidia-egl-wayland-common            384.98-3                     amd64        NVIDIA binary Wayland EGL external platform - common files
ii  nvidia-egl-wayland-icd:amd64         384.98-3                     amd64        NVIDIA Wayland EGL external platform library (ICD)
ii  nvidia-kernel-dkms                   384.98-3                     amd64        NVIDIA binary kernel module DKMS source
ii  nvidia-kernel-support                384.98-3                     amd64        NVIDIA binary kernel module support files
ii  nvidia-legacy-check                  384.98-3                     amd64        check for NVIDIA GPUs requiring a legacy driver
ii  nvidia-modprobe                      384.98-1                     amd64        utility to load NVIDIA kernel modules and create device nodes
ii  nvidia-persistenced                  384.98-1                     amd64        daemon to maintain persistent software state in the NVIDIA driver
ii  nvidia-settings                      384.98-1                     amd64        tool for configuring the NVIDIA graphics driver
ii  nvidia-vdpau-driver:amd64            384.98-3                     amd64        Video Decode and Presentation API for Unix - NVIDIA driver
ii  nvidia-vulkan-common                 384.98-3                     amd64        NVIDIA Vulkan driver - common files
ii  nvidia-vulkan-icd:amd64              384.98-3                     amd64        NVIDIA Vulkan installable client driver (ICD)
ii  xserver-xorg-video-nvidia            384.98-3                     amd64        NVIDIA binary Xorg driver
```

**Comment by bluca** [comment] 2017-12-05 14:59
Are you really sure you installed bumblebee and primus from the sid repositories? There's an explicit breaks with libgl1-nvidia-glvnd-glx so it's not possible.

Anyway, you need to switch to the non-glvnd packages - should be doable with:
```sudo apt install libgl1-nvidia-glx libegl1-nvidia nvidia-nonglvnd-vulkan-common```

**Comment by FateRover** [comment] 2017-12-05 15:04
yeah  i have realized it and install libgl1-nvidia-glx after lastpost    and type the result ,and you have replyme, lol.  but  the fps(45) is lower than   old version (60fps)

**Comment by bluca** [comment] 2017-12-05 15:29
AFAIK there is a known performance regression in the 381 to 387 series - it's due to the drivers.

Given the issue is solved I'll close this now.

**Closed by bluca** 2017-12-05 15:29 UTC
