### ISSUE TITLE
Bumblebee not disabling nvidia graphics after upgrade to kernel 4.4.7

### ISSUE THREAD

**Issue by marmistrz** [Bumblebee-Project/Bumblebee#758] opened 2016-04-17 19:50 UTC
Although the dmesg log claim bbswitch did it. Happened once, disappeared after reboot

**Comment by HileV** [comment] 2016-04-17 19:58
Upgrade ur kernel to 4.5

**Comment by marmistrz** [comment] 2016-04-19 14:49
4.4.7 is the lts kernel for Arch, I'm not a fan of frequent kernel upgrades. 
It's happening for me once again

**Comment by marmistrz** [comment] 2016-04-19 17:19
Ok, I see, the problem is that the nvidia_drm module is not loaded, which depends on nvidia_modeset.

**Comment by ArchangeGabriel** [comment] 2016-05-06 12:26
Dupe of #719.

**Closed by ArchangeGabriel** 2016-05-06 12:26 UTC
