### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by pmatos** [Bumblebee-Project/Bumblebee#914] opened 2017-09-04 12:38 UTC
Last commit to the project was in 2013. Is this project still active?

**Comment by gsgatlin** [comment] 2017-09-04 13:13
May wish to see https://github.com/Bumblebee-Project/Bumblebee/issues/710

**Comment by Lekensteyn** [comment] 2017-09-04 22:15
The master branch reflects the latest released version, there is also a develop branch which accumulates all work so far.

Yes, project development is pretty dormant, but the base program is quite stable. Most annoyance comes from driver issues (and integration with distributions), people like @gsgatlin and @bluca (thank you!) help a lot here. Another unsolved issue is related to power management for "newer" laptops causing lockups, but that really needs some expert to look into.

Closing as duplicate of #710.

**Closed by Lekensteyn** 2017-09-04 22:15 UTC
