### ISSUE TITLE
Cannot turn off nvidia after primusrun

### ISSUE THREAD

**Issue by HumbleJosh** [Bumblebee-Project/Bumblebee#760] opened 2016-04-30 01:22 UTC
Hello,

I know that I should modprobe -r nvidia_modeset for this. Which works perfectly.
But is there a way to make it automatic?

**Comment by oanonymos0** [comment] 2016-05-02 14:57
You could make a shell script: **my_primusrun**, and in there put these 2 lines"

primusrun "$@"
modprobe -r nvidia_modeset


then make it executable (chmod +x shell_script)
finally put the bash directory in your path like [this](http://askubuntu.com/questions/60218/how-to-add-a-directory-to-my-path)
then everytime you need primusrun, you can run your bash script instead (**my_primusrun**  %command% on steam)

**Comment by ArchangeGabriel** [comment] 2016-05-06 12:27
Dupe of #719. Should be fixed by #762.

**Closed by ArchangeGabriel** 2016-05-06 12:27 UTC
