### ISSUE TITLE
Fedora + nouveau (+DRI3)

### ISSUE THREAD

**Issue by MalcolmMielle** [Bumblebee-Project/Bumblebee#582] opened 2014-05-26 16:50 UTC
Hello,

Optirun used to work out of the box but now, when I try to run `optirun glxinfo` I have this output before a crash : 

    name of display: :0
    [VGL] ERROR: glXCreateContextAttribsARB symbol not loaded

Same if I try to run some games with optirun on Wine. The game work fine without it.

I'm using fedora20 with nouveau and `bumblebee.x86_64    3.2.1-4.fc20`

thanks a lot !

**Comment by ArchangeGabriel** [comment] 2015-01-01 21:54
Please keep the discussion here about nouveau, for NVIDIA and SELinux see #619. Can someone facing the issue with nouveau post the full Xorg.8.log?

**Comment by gsgatlin** [comment] 2015-01-08 18:36
Greetings.

So as far as I can tell bumblebee + nouveau broke in fedora 18. And we are on fedora 21 now.

So to make sure I am not crazy, I did a EOL install of fedora 17 on my spare notebook. nouveau does indeed work on this system, with the caveat that I have to install the "acpi handle hack" module because this is before that kernel bug got fixed in Red Hat. It was fixed in fedora 18+

(See https://bugzilla.redhat.com/show_bug.cgi?id=903360)

So here are some links to files after successfully running:

optirun -b virtualgl glxgears -info

on that fedora 17 box I installed this morning. It was fully updated to where Red Hat cut off support for fedora 17. So its kernel 3.9.10-100.fc17.x86_64. (Kind of old)

Support ended for fedora 17 on 30th July 2013.

Fedora 17: (WORKING)
/var/log/messages:
http://pastebin.com/MDU8dDvD
/var/log/Xorg.8.log:
http://pastebin.com/jeRDvMK6

Remember this is working good. No nvidia driver installed. Pure nouveau setup. I do also have bbswitch installed. I assume that shall not be an issue. I wanted to provide these logs just so you have something to compare it to where its was working in fedora distro. Even its its old.

Ok, so lets now wipe this laptop and put fedora 21 on it...
Using the fedora 21 MATE spin live DVD to re-install the box.

So the first thing I notice about fedora 21 on the first boot with bumblebee and bbswitch installed is that bumblebeed.service is running and that the card is still on even though I think it should be off:

[root@y470c ~]# cat /proc/acpi/bbswitch 
0000:01:00.0 ON

The error message on the console in fedora 21:


[gsgatlin@y470c ~]$ optirun -b virtualgl glxgears -info
[  242.847761] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) systemd-logind: failed to get session: PID 1885 does not belong to any known session

[  242.847833] [ERROR]Aborting because fallback start is disabled.

Fedora 21: (NOT WORKING)
/var/log/messages:
http://pastebin.com/watLc4AE
/var/log/Xorg.8.log:
http://pastebin.com/DF7gGrtJ

Kernel version is 3.17.7-300.fc21.x86_64.

Please let me know if you require further information?

Thanks.

**Comment by gsgatlin** [comment] 2015-01-08 19:50
Forgot to mention that selinux was disabled on the fedora 21 example above. So the problem is not selinux related at all. Thanks.

**Comment by gsgatlin** [comment] 2015-01-08 20:15
I don't know if this is helpful, but google showed me this:

http://nouveau.freedesktop.org/wiki/TroubleShooting/#index1h3

I found this site which suggests ways to see kernel parameters:

http://serverfault.com/questions/62316/how-do-i-list-loaded-linux-module-parameter-values

So I ran it on the fc21 box. Here is the output from the nouveau part:

Module: nouveau
Parameter: agpmode --> -1
Parameter: config --> (null)
Parameter: debug --> (null)
Parameter: duallink --> 1
Parameter: ignorelid --> 0
Parameter: modeset --> -1
Parameter: noaccel --> 0
Parameter: nofbaccel --> 0
Parameter: pstate --> 0
Parameter: runpm --> -1
Parameter: tv_disable --> 0
Parameter: tv_norm --> (null)
Parameter: vram_pushbuf --> 0


modinfo shows me these possible parameters:

[root@y470c ~]# modinfo nouveau
filename:       /lib/modules/3.17.7-300.fc21.x86_64/kernel/drivers/gpu/drm/nouveau/nouveau.ko.xz
license:        GPL and additional rights
description:    nVidia Riva/TNT/GeForce/Quadro/Tesla
author:         Nouveau Project
alias:          pci:v000012D2d*sv*sd*bc03sc*i*
alias:          pci:v000010DEd*sv*sd*bc03sc*i*
depends:        drm,drm_kms_helper,ttm,mxm-wmi,wmi,video,i2c-algo-bit
intree:         Y
vermagic:       3.17.7-300.fc21.x86_64 SMP mod_unload 
signer:         Fedora kernel signing key
sig_key:        A3:DE:AA:E7:2F:85:C6:30:29:D7:87:90:41:C6:33:43:8A:40:E6:88
sig_hashalgo:   sha256
parm:           pstate:enable sysfs pstate file, which will be moved in the future (int)
parm:           tv_norm:Default TV norm.
		Supported: PAL, PAL-M, PAL-N, PAL-Nc, NTSC-M, NTSC-J,
			hd480i, hd480p, hd576i, hd576p, hd720p, hd1080i.
		Default: PAL
		*NOTE* Ignored for cards with external TV encoders. (charp)
parm:           tv_disable:Disable TV-out detection (int)
parm:           ignorelid:Ignore ACPI lid status (int)
parm:           duallink:Allow dual-link TMDS (default: enabled) (int)
parm:           nofbaccel:Disable fbcon acceleration (int)
parm:           agpmode:AGP mode (0 to disable AGP) (int)
parm:           vram_pushbuf:Create DMA push buffers in VRAM (int)
parm:           config:option string to pass to driver core (charp)
parm:           debug:debug string to pass to driver core (charp)
parm:           noaccel:disable kernel/abi16 acceleration (int)
parm:           modeset:enable driver (default: auto, 0 = disabled, 1 = enabled, 2 = headless) (int)
parm:           runpm:disable (0), force enable (1), optimus only default (-1) (int)

I wonder if the runpm param could be the problem? Although I have no clue how it could be changed.

I did not see any kernel arguments in grub dealing with nouveau on this system. Cheers.

**Comment by ArchangeGabriel** [comment] 2015-01-17 22:02
You can try different value by adding `nouveau.runpm=0` (change 0 to 1 if you want to test this one) to your kernel cmdline.

But as a matter of fact, I’ve finished debugging my setup (although currently I’m stucked with https://bugs.freedesktop.org/show_bug.cgi?id=87942, making me doubting about the fact I ever had it working and not only LLVMpipe instead), and learned a lot of things in the way.

So, I have a lots of things to make you try.

My first guess is PRIME and/or DRI3. Do you have bumblebee-nvidia installed when you try nouveau? Whatever is your answer to this question, do you still have nouveau blacklisted on boot when you do that? Can you provide a full dmesg from a fresh boot followed by an optirun attempt on nouveau (with your current setup, regardless of my previous questions), and both Xorg.0 and .8 logs?

**Comment by gsgatlin** [comment] 2015-01-18 18:39
Hi. Thanks a lot for looking into this question whether it ends up being possible or not.

I may have messed up my spare computer so today I did a fresh install. No bumblebee-nvidia installed. Its a pure nouveau rig (No nvidia driver) so I was not aware nouveau needed to be blacklisted. So I made sure that it is now. Added to (/usr/lib/modprobe.d/dist-blacklist.conf)

Before running for the first time I tested with:

[root@localhost ~]# cat /proc/acpi/bbswitch 
0000:01:00.0 ON

[root@localhost ~]# lsmod | grep nouveau
[root@localhost ~]# 

Also disabled selinux before running test...

[gsgatlin@localhost ~]$ optirun -b virtualgl glxgears -info
[  224.048816] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) systemd-logind: failed to get session: PID 1957 does not belong to any known session

[  224.048920] [ERROR]Aborting because fallback start is disabled.

dmesg:

http://pastebin.com/s22pHw02

Xorg.0.log:

http://pastebin.com/eK2CtjmB

Xorg.8.log:

http://pastebin.com/2CcCnDaa

Let me know if there is anything else I should try? I will leave the spare machine alone for now in case anything needs to be changed on it and re-tested.

**Comment by ArchangeGabriel** [comment] 2015-01-18 18:46
Hum, nouveau didn’t load at all, you’re probably blacklisting it too much. Blacklisting is needed for primary X server not to grab it on start. What happen if you stop bumblebee and try to modprobe it manually (with -v option)? Especially in dmesg.

Remove everything about nouveau in your cmdline, just keep a `/etc/modprobe.d/bumblebee.conf` with `blacklist nouveau` and remember to update your initramfs before rebooting.

**Comment by gsgatlin** [comment] 2015-01-18 18:47
One other thing. After trying optirun, I see nouveau is loaded now. But the special X on display 8 did not start.

[gsgatlin@localhost ~]$ lsmod | grep nouveau
nouveau              1340938  0 
ttm                    84882  1 nouveau
i2c_algo_bit           13250  2 i915,nouveau
drm_kms_helper         93604  2 i915,nouveau
drm                   300858  6 ttm,i915,drm_kms_helper,nouveau
mxm_wmi                12865  1 nouveau
video                  19825  2 i915,nouveau
wmi                    18820  2 mxm_wmi,nouveau

If I reboot its not loaded any longer.

[gsgatlin@localhost ~]$ lsmod | grep nouveau
[gsgatlin@localhost ~]$ cat /proc/acpi/bbswitch 
0000:01:00.0 OFF

If I try to run optirun again it changes:

[gsgatlin@localhost ~]$ cat /proc/acpi/bbswitch 
0000:01:00.0 ON
[gsgatlin@localhost ~]$ lsmod | grep nouveau
nouveau              1340938  0 
ttm                    84882  1 nouveau
i2c_algo_bit           13250  2 i915,nouveau
drm_kms_helper         93604  2 i915,nouveau
drm                   300858  6 ttm,i915,drm_kms_helper,nouveau
mxm_wmi                12865  1 nouveau
video                  19825  2 i915,nouveau
wmi                    18820  2 mxm_wmi,nouveau


But it doesn't open the glxgears window. Just keep seeing that systemd-logind: failed to get session: PID XXXX does not belong to any known session error.

**Comment by ArchangeGabriel** [comment] 2015-01-18 18:48
Ignore the systemd-logind error, it’s only noise. Take a look at my former message.

**Comment by gsgatlin** [comment] 2015-01-18 19:07
Ok. I removed any references I made on the cmdline with grub2 and also removed the entry from
/usr/lib/modprobe.d/dist-blacklist.conf

Verified nouveau is loaded after a reboot. Verified there is nothing in kernel args about nouveau from within grub itself.

 Next created a /etc/modprobe.d/bumblebee.conf
with 
blacklist nouveau

and reboot again.

Root shell output:

http://pastebin.com/uG3vRDd7

dmesg:

http://pastebin.com/QL7NPPFf

Xorg.0.log:

http://pastebin.com/vWaMbc2V

Xorg.8.log:

http://pastebin.com/17Z3tPmj

Let me know if I should try anything else? Thanks.

**Comment by gsgatlin** [comment] 2015-01-18 19:31
Alright. I edited

/etc/dracut.conf

and added

# dracut modules to omit
omit_dracutmodules+="nouveau"

and ran

[root@localhost ~]# dracut --force

This should have updated my initramfs. So then I rebooted.

But it did seem to help. But here are the logs anyways.

Root shell output:
http://pastebin.com/D6VxSsva

dmesg:
http://pastebin.com/0nhf3YvQ

Xorg.0.log:
http://pastebin.com/fu31JsRg

Xorg.8.log:
http://fpaste.org/171155/09403142/
(Can't use patebin as I ran over their free usage now...)

Let me know if there is anything else I should try? Thanks.

**Comment by gsgatlin** [comment] 2015-01-18 19:41
Sorry, The root shell output is wrong in my last post. Here is the correct paste:

Root shell output:

http://fpaste.org/171156/42160986/

dmesg:

http://fpaste.org/171157/21609996/

Xorg.0.log:

http://fpaste.org/171158/42161000/

Xorg.8.log:

http://fpaste.org/171159/16100971/

Sorry for the confusion.

**Comment by gsgatlin** [comment] 2015-01-18 19:47
Also, I had a typo above. While adding the nouveau module to modules to omit from the initramfs in dracut.conf seemed to help a bit with the Xorg.0.log its still not working properly. I will leave the laptop alone until I hear back on anything to change on it. Thanks.

**Comment by ArchangeGabriel** [comment] 2015-01-18 19:54
OK, we’re getting better, as I supposed you’re still having primary Xorg taking the second card.

Could you add a /etc/X11/xorg.conf.d/10-disable_prime.conf file containing this:

```
Section "ServerLayout"
    Identifier  "Layout0"
    Option      "AutoAddGPU" "false"
EndSection
```

**Comment by gsgatlin** [comment] 2015-01-18 20:12
So right now the only file in there (/etc/X11/xorg.conf.d/) is 00-keyboard.conf
So added a 10-disable_prime.conf with the contents you specified.

Rebooted laptop and tried again.

Root shell output:

http://fpaste.org/171165/14216117/

dmesg:

http://fpaste.org/171167/11851142/

Xorg.0.log:

http://fpaste.org/171168/21611886/

Xorg.8.log:

http://fpaste.org/171170/42161192/

Let me know if there is anything else I should change on this system? Still doesn't work. Thanks a lot.

**Comment by ArchangeGabriel** [comment] 2015-01-18 20:16
OK, modesetting is ignoring this option. Could you blacklist or uninstall modesetting (and in the same raw, vesa and fbdev)?

**Comment by gsgatlin** [comment] 2015-01-18 20:24
Please excuse my ignorance but should I add 

nouveau.modeset=0

to kernel boot options in grub?

Also, I should remove raw, vesa and fbdev from the initramfs the same way I did the nouveau driver?
 
And add  to  /etc/modprobe.d/bumblebee.conf as well?

blacklist raw
blacklist vesa
blacklist fbdev

Just want to make sure I'm making the correct changes.

Thanks.

**Comment by ArchangeGabriel** [comment] 2015-01-18 20:31
Hum, sorry, my message wasn’t very clear (especially because "in the same raw” does not seems to exist as an expression).

Kernel boot options don’t need to be tweaked here.

You should either uninstall (I mean remove the installed packages, probably under xorg-video-* or xf86-video-*, but I think you will be better at knowing what are the corresponding packages on Fedora) or blacklist (by adding them as you’ve described juste above to bumblebee.conf and updating initramfs) the following modules:
modesetting
vesa
fbdev

**Comment by gsgatlin** [comment] 2015-01-18 20:35
Hi, There doesn't seem to be a "modesetting" module loaded.

[gsgatlin@localhost ~]$ lsmod | grep modesetting
[gsgatlin@localhost ~]$ 

I think all drivers in fedora use kms. I don't think its easily switched. See for example:

http://fedoraproject.org/wiki/Features/KernelModesetting (That was fedora 10 and we are on 21 now)

But I will try to google some more or ask on #fedora.

**Comment by gsgatlin** [comment] 2015-01-18 20:38
I guess maybe I need nomodeset as a argument to disable modesetting.

**Comment by gsgatlin** [comment] 2015-01-18 20:42
***nirik notes if you pass 'nomodeset' you will get the vesa driver. nouveau won't load. 

Not sure if thats what we want.

**Comment by ArchangeGabriel** [comment] 2015-01-18 20:49
Hum, I didn’t know KMS was that tricky. I personally uninstalled those packages on my setup, but that’s because I’m confident in the fact I will ever be able to manage a non-starting X. You might want to try nomodeset for modesetting this way (in bumblebee.conf):
```
blacklist modesetting
options modesetting modeset=0
```

**Comment by gsgatlin** [comment] 2015-01-18 21:10
Ok. Added to the bottom of the file:

KernelDriver=nouveau
PMMethod=auto
XorgConfFile=/etc/bumblebee/xorg.conf.nouveau
blacklist modesetting
options modesetting modeset=0

Gave me an error. 

[  104.087572] [ERROR]Invalid configuration: no driver configured.

So I removed it. Then it started properly. Does it need to go in another section of bumblebee.conf then at the very bottom?

Added the following kernel options:

nouveau.modeset=0 nomodeset

nomodeset is described as doing:

nomodeset - this will disable the kernel modesetting feature and drop the user back to the old X.org infrastructure and behaviour.

When I rebooted, plymouth was all "texty" as the system booted and my resolution is lower now. (1024x768 instead of 1366x768)

Root shell output:

http://fpaste.org/171180/15039142/

dmesg:

http://fpaste.org/171181/14216151/

Xorg.0.log:

http://fpaste.org/171182/21615271/

Xorg.8.log:

http://fpaste.org/171184/16153321/

Let me know if there is anything else you think I could try with this.

**Comment by gsgatlin** [comment] 2015-01-18 21:28
So I tried changing the kernel args to just:

nouveau.modeset=0 

and I removed the nomodeset option.

This gets me a xorg.0 that is intel again instead of vesa.. My screen resolution went back to normal. I don't think there is a way to get the intel driver to load without kms. I think its just a fedorq quirk. Oh well.


Root shell output:
http://fpaste.org/171188/42161600/
dmesg:
http://fpaste.org/171189/61610114/
Xorg.0.log:
http://fpaste.org/171190/42161624/
Xorg.8.log:
http://fpaste.org/171191/61631814/

**Comment by gsgatlin** [comment] 2015-01-18 21:31
The line in Xorg.8.log is kind of interesting. 

(EE) [drm] KMS not enabled

Not sure why it matters for drm.

**Comment by ArchangeGabriel** [comment] 2015-01-18 21:36
OK sorry, I have been unclear again. It was /etc/modprobe.d/bumblebee.conf. Please remove everything you’ve added to kernel cmdline about modeset.

**Comment by gsgatlin** [comment] 2015-01-18 21:49
Ok, sure. /etc/modprobe.d/bumblebee.conf now has:

blacklist nouveau
blacklist modesetting
options modesetting modeset=0

Rebooted laptop after removing nouveau.modeset=0 from grub boot args and running 

grub2-mkconfig -o /boot/grub2/grub.cfg

Root shell output:
http://fpaste.org/171195/17463142/
dmesg:
http://fpaste.org/171196/42161760/
Xorg.0.log:
http://fpaste.org/171197/42161765/
Xorg.8.log:
http://fpaste.org/171198/61770814/

Still doesn't work. Let me know if there is something else I should try? Thanks.

**Comment by ArchangeGabriel** [comment] 2015-01-18 21:52
Did you rebuild initramfs? (`dracut -f /boot/initramfs-currentimage` where `initramfs-currentimage` is replaced with the name of the image you are currently using; this is necessary after changes in /etc/modprobe.d)

Because currently this is still failing because of the modesetting driver being loaded.

**Comment by gsgatlin** [comment] 2015-01-18 22:11
Ok.  dracut.conf has:

omit_dracutmodules+="nouveau modesetting"

And I ran dracut -f and rebooted.

It seems to have not helped. I do not why. I am sorry.

Root shell output:
http://fpaste.org/171203/21618534/
dmesg:
http://fpaste.org/171204/14216186/
Xorg.0.log:
http://fpaste.org/171205/42161871/
Xorg.8.log:
http://fpaste.org/171207/21618800/

rpm -qf /usr/lib64/xorg/modules/drivers/modesetting_drv.so
xorg-x11-drv-modesetting-0.9.0-2.fc21.x86_64

I will try removing the package....

**Comment by gsgatlin** [comment] 2015-01-18 22:29
Hmnn. Removing the rpm xorg-x11-drv-modesetting rpm seems to get things working finally. But I'm not sure how to fix the issue other then making sure that package isn't installed. bbswitch and bumblebee seem to be working correctly as far as power management goes.

http://i.imgur.com/EOOXxMP.png

Root shell output:
http://fpaste.org/171212/61952214/
dmesg:
http://fpaste.org/171213/61968914/
Xorg.0.log:
http://fpaste.org/171214/21619798/
Xorg.8.log:
http://fpaste.org/171215/19874142/

Perhaps I could make the bumblebee rpm conflict with xorg-x11-drv-modesetting ?

**Comment by ArchangeGabriel** [comment] 2015-01-18 22:38
I’m not sure this is a good policy. The other option is just to document that issue.

Another alternative would be to add a metapackage bumblebee-nouveau that is conflicting with xorg-x11-drv-modesetting, and make bumblebee recommend (or corresponding FC mechanism) this package.

On an other topic, don’t your bumblebee package provide /etc/modprobe.d/bumblebee.conf with:
```
blacklist nvidia
blacklist nouveau
```
This sould be the case, if not please add it.

**Comment by gsgatlin** [comment] 2015-01-18 22:43
Just tested one more oddity and it seems that auto detection does not work. Like if in /etc/bumblebee/bumblebee.conf

Driver=

bumblebeed won't start. It gives the error:

[   92.230439] [ERROR]Invalid configuration: no driver configured.

But if I change it to

Driver=nouveau

then it works ok. I think auto detection is working ok for nvidia setup however.

Ok. I will ponder adding a bumblebee-nouveau package to handle that use case. And no, my rpms do not add a /etc/modprobe.d/bumblebee.conf with 

blacklist nvidia
blacklist nouveau

But I will try to add that soon. 

[gsgatlin@y470 ~]$ rpm -ql bumblebee
/etc/bash_completion.d/bumblebee
/etc/bumblebee
/etc/bumblebee/bumblebee-nouveau.conf
/etc/bumblebee/bumblebee.conf
/etc/bumblebee/xorg.conf.d/10-dummy.conf
/etc/bumblebee/xorg.conf.nouveau
/etc/bumblebee/xorg.conf.nvidia
/etc/systemd/system/bumblebeed.service
/usr/bin/bumblebee-bugreport
/usr/bin/optirun
/usr/lib/systemd/system/bumblebeed.service
/usr/lib/udev/rules.d/99-bumblebee-nvidia-dev.rules
/usr/sbin/bumblebeed
/usr/share/doc/bumblebee/README.markdown
/usr/share/doc/bumblebee/RELEASE_NOTES_3_2_1
/usr/share/man/man1/bumblebeed.1.gz
/usr/share/man/man1/optirun.1.gz

Thanks a lot for all your patience with me and your work on figuring out what was wrong.

**Comment by ArchangeGabriel** [comment] 2015-01-18 22:46
I’m not sure about auto-detect, will look at it. Please tell me when the packages will be done, so that I can close this issue.

**Comment by gsgatlin** [comment] 2015-01-18 22:47
I will try to work on it on Tuesday. Thanks.

**Comment by gsgatlin** [comment] 2015-01-20 22:16
@MalcolmMielle can you try using yum or dnf to install 

bumblebee-nouveau

And see if that solves your issue? You will need to un-install xorg-x11-drv-modesetting and bumblebee-nvidia for this to work. Unfortunately there are SELinux issues similar to the closed driver usage so you will need to use permissive mode until it is figured out further. bumblebee-nouveau contains a selinux module that is similar to but not exactly like the one in bumblebee-nvidia.


bumblebee-3.2.1-7 fixes the issues with /etc/modprobe.d/bumblebee.conf  


[gsgatlin@y470 specs]$ rpm -ql bumblebee
/etc/bash_completion.d/bumblebee
/etc/bumblebee
/etc/bumblebee/bumblebee-nouveau.conf
/etc/bumblebee/bumblebee.conf
/etc/bumblebee/xorg.conf.d/10-dummy.conf
/etc/bumblebee/xorg.conf.nouveau
/etc/bumblebee/xorg.conf.nvidia

/etc/modprobe.d/bumblebee.conf

/etc/systemd/system/bumblebeed.service
/usr/bin/bumblebee-bugreport
/usr/bin/optirun
/usr/lib/systemd/system/bumblebeed.service
/usr/lib/udev/rules.d/99-bumblebee-nvidia-dev.rules
/usr/sbin/bumblebeed
/usr/share/doc/bumblebee/README.markdown
/usr/share/doc/bumblebee/RELEASE_NOTES_3_2_1
/usr/share/man/man1/bumblebeed.1.gz
/usr/share/man/man1/optirun.1.gz

It was pushed out yesterday and can be upgraded any time.

Thanks.

**Comment by gsgatlin** [comment] 2015-01-20 22:20
Also, I notice auto detection works if I don't install bbswitch. I can open a new issue for the auto detection stuff if you wish.

**Comment by ArchangeGabriel** [comment] 2015-01-20 22:21
Please do so.

**Comment by osamak** [comment] 2015-01-26 16:55
So for those who aren't keen on the details, what has changed with the most recent update? (I still have my nvidia card turned on all the time.)

**Comment by gsgatlin** [comment] 2015-01-26 19:32
I have tested bumblebee-nouveau on fedora 21, fedora 20, CentOS 7. I could not get it to work with CentOS 6.  It seems to work correctly on all the distros except for CentOS 6. I did see a warning under CentOS 7 that says:

Error: nConfigOptions (12) does not match the actual number of options in
       __driConfigOptions (13).

But it seems to still work ok. I am unsure how to tell if the card is on/off without bbswitch installed but with bbswitch installed card seems to turn on/off for me ok using nouveau on fedora20/21/centos7.

@ArchangeGabriel Sorry but after a lot of testing I could not reproduce the auto detection problem. It must have been something I did when you were troubleshooting this issue. So I think it was just a weird one off situation. Auto detection seems to be working fine now.

@osamak So if you are using the nouveau driver you now need to install the rpm package bumblebee-nouveau on fedora 20/21 and also CentOS 7. And you will need to reboot.  I guess if you are having a problem with your card never turning off you maybe should open a new issue? This issue was created for people having a hard time getting nouveau to work with the bumblebee software in fedora.

**Comment by ArchangeGabriel** [comment] 2015-02-16 21:32
I was going to close this issue, but then I saw that modesetting is now built-in starting with xorg 1.17. Can you test and report if it still work with it? If not, I think it’s time to discuss this with xorg devs.

**Comment by gsgatlin** [comment] 2015-02-16 22:37
I was actually able to test this today because of a different issue. (SELinux) which I will comment on shortly in a couple of other issues.

It is working for me but fedora 21 is on xorg1.16.3 so I don't know how helpful that would be to you?

See also:

 https://lists.fedoraproject.org/pipermail/devel/2015-February/207739.html

So I guess I could test it in like a week or two?

**Comment by ArchangeGabriel** [comment] 2015-02-16 22:39
Yes indeed. Will hold this until it can be tested and confirmed working or not.

**Comment by ArchangeGabriel** [comment] 2015-04-09 09:34
Any news here? Has 1.17 landed somewhere? What about DRI3 then?

**Comment by gsgatlin** [comment] 2015-05-22 19:12
It looks like bumblebee-nouveau rpm / optirun with nouveau driver works on fedora 22 even with /usr/lib64/xorg/modules/drivers/modesetting_drv.so bundled within xorg-x11-server-Xorg as a virtual package. I'm pleasantly surprised this actually worked. There are still more selinux issues I have to try to figure out however. I'll see how far I can get with that this afternoon.

In fedora 22 we have xorg-x11-server-Xorg-1.17.1-11.fc22.x86_64

In fedora 21 we have xorg-x11-server-Xorg-1.16.3-2.fc21.x86_64 still.

Hope this was helpful.

**Comment by ArchangeGabriel** [comment] 2015-12-27 22:29
OK, nice. Closing this then.

**Closed by ArchangeGabriel** 2015-12-27 22:29 UTC
Labels: Bug, Discussion, NeedInfo, P:Medium
