### ISSUE TITLE
Numpad not working when an application is started with primusrun/optirun

### ISSUE THREAD

**Issue by gitterrost4** [Bumblebee-Project/Bumblebee#470] opened 2013-09-07 15:57 UTC
When I start an application with primusrun, my Numpad behaves as if numlock is off. Pressing the Numlockbutton has no effect on the situation. However Pressing and holding the Numlock button and then pressing a number (while still holding down Numlock) produces the correct number.

This problem only seems to arise, when the program started with primusrun actually uses opengl. For instance: Starting the minecraft launcher does not have any effect and the numpad behaves as expected. However, once minecraft starts (and hence uses 3D accelleration), the numpad shows the behavior described above.

Do you need any output of any commands?

**Comment by ArchangeGabriel** [comment] 2015-02-16 21:37
Re-opening because of #629.

**Comment by ArchangeGabriel** [comment] 2015-04-09 09:29
So, @pando85 or @gitterrost4, what the status here?

**Comment by pando85** [comment] 2015-04-11 07:39
I think you can close it.
I can't reproduce the bug in version 3.2.1 
Thanks for all.

**Closed** 2015-04-12 13:53 UTC
Labels: NeedInfo
