### ISSUE TITLE
Issues with releasing discrete gpu with cuda toolkit installed

### ISSUE THREAD

**Issue by AudioTropic** [Bumblebee-Project/Bumblebee#630] opened 2015-01-29 15:44 UTC
I have gone through alot of issues and cannot find a solution to this issue or one similar to it. I currently have a GTX 860M and Intel Integrated graphics and when I boot i successfully get bumblebee to start and to disable the 860m and have no issues using cat /proc/acpi/bbswitch which returns it is OFF now when I run the deviceQuery script in the NVIDIA Cuda toolkit samples my device passes but when i check to see if the discrete card is disabled I find that it cannot disable it and that a bug is raised in the Xorg-X11-Server. I have already blacklisted nvidia and nouveau in /etc/modprob.b/blacklist.conf and with other files through my troubleshooting and others guides. I will post some outputs you may find useful if you need any others ask and I will post them ASAP.

```
[root@localhost deviceQuery]# optirun ./deviceQuery 
./deviceQuery Starting...
 CUDA Device Query (Runtime API) version (CUDART static linking)
libkmod: kmod_config_parse: /etc/modprobe.d/bumblebee.conf line 3: ignoring bad line starting with 'bbswitch'
Detected 1 CUDA Capable device(s)
Device 0: "GeForce GTX 860M"
  CUDA Driver Version / Runtime Version          6.5 / 6.5
  CUDA Capability Major/Minor version number:    3.0
  Total amount of global memory:                 4096 MBytes (4294770688 bytes)
  ( 6) Multiprocessors, (192) CUDA Cores/MP:     1152 CUDA Cores
  GPU Clock rate:                                915 MHz (0.92 GHz)
  Memory Clock rate:                             2500 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 262144 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Bus ID / PCI location ID:           1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 6.5, CUDA Runtime Version = 6.5, NumDevs = 1, Device0 = GeForce GTX 860M
Result = PASS
```

```
[root@localhost deviceQuery]# dmesg | grep bbswitch
[   12.773380] bbswitch: module verification failed: signature and/or  required key missing - tainting kernel
[   12.773548] bbswitch: version 0.8
[   12.773551] bbswitch: Found integrated VGA device 0000:00:02.0: \_SB_.PCI0.GFX0
[   12.773554] bbswitch: Found discrete VGA device 0000:01:00.0: \_SB_.PCI0.PEG0.PEGP
[   12.773628] bbswitch: detected an Optimus _DSM function
[   12.773668] bbswitch: Succesfully loaded. Discrete card 0000:01:00.0 is on
[   28.400953] bbswitch: disabling discrete graphics
[  580.157927] bbswitch: enabling discrete graphics
</code>
<code>
[root@localhost deviceQuery]# cat /proc/acpi/bbswitch 
0000:01:00.0 ON
```

Edit: Running optirun glxspheres or any of the programs works with turning the discrete card on and off

**Comment by excieve** [comment] 2015-02-02 23:54
It seems to be a duplicate of #565.

**Closed** 2015-02-03 03:40 UTC
