### ISSUE TITLE
glx x server module not loading with bumblebee-nvidia

### ISSUE THREAD

**Issue by balister** [Bumblebee-Project/Bumblebee#634] opened 2015-02-12 14:28 UTC
From the Xorg.8 logfile. The missing file seems suspicious. INstalled via the RPMs on Feb 11/12, 2015

Fedora 21, Lenovo Y50-70.
```
[    75.186] (II) LoadModule: "glx"
[    75.198] (II) Loading /usr/lib64/nvidia-bumblebee/xorg/modules/extensions/libglx.so
[    75.235] (EE) Failed to load /usr/lib64/nvidia-bumblebee/xorg/modules/extensions/libglx.so: libnvidia-tls.so.346.35: cannot open shared object file: No such file or directory
[    75.235] (II) UnloadModule: "glx"
```

**Comment by gsgatlin** [comment] 2015-02-12 20:02
I'm really sorry but I don't know why this is happening. I can confirm on a fresh install X is broken. It is very strange. My laptop is still working but maybe it will break soon. But my laptop is fully up to date with dnf.

**Comment by gsgatlin** [comment] 2015-02-12 20:51
Ok, one problem is that /lib/libGL.so.1 is a symlink to /usr/lib64/nvidia-bumblebee/libGL.so.1 and needed to be deleted. But its still not enough to fix the problems with optirun/primusrun. I will continue to try to troubleshoot as time permits. I think I need to re-install this box before I post any logs.

**Comment by balister** [comment] 2015-02-12 20:59
Thanks, let me know if I can help. This is a fresh install and I can start over if needed.  Do you know an easy place for me to get the missing file to see if that helps?

**Comment by gsgatlin** [comment] 2015-02-13 15:58
Making some progress here. I don't mean to sound so cryptic but should have more info by end of day today. Make sure you have selinux set to permissive in /etc/sysconfig/selinux which is s step I forgot. But there may be more going on here with "multilib" that needs to get fixed. I should have more time to look at later today after some RHEL 7 work I gotta do.

**Comment by balister** [comment] 2015-02-13 18:49
Setting SELinux to permissive gets me a running glxgears with optirun. Next to try eve with wine :)

**Comment by ArchangeGabriel** [comment] 2015-02-16 22:16
Did it worked with WINE?

Seems to be #619 again then.

**Comment by balister** [comment] 2015-02-16 22:30
After setting selinux to permissive it works with glxspheres and wine. I
run Eve with wine.

**Comment by ArchangeGabriel** [comment] 2015-02-16 22:36
OK, closing, duplicate of #633 and #619.

**Closed by ArchangeGabriel** 2015-02-16 22:36 UTC

**Comment by gsgatlin** [comment] 2015-02-16 23:55
Also, juts as a follow up bumblebee should work now with selinux in enforcing mode or permissive mode  with bumblebee-nvidia-346.35-3. Cheers,

**Comment by elHippieCosmico** [comment] 2015-10-21 18:28
Hello! I'm using Fedora 21 on an asus laptop with nvidia geforce 620M and the bumblebee-nvidia-352.55.4 driver. Changing selinux to permissive mode fix the problem for me too, but I think it's not very convenient  to use selinux permanently in that mode... It seems that it's some problem with the bumblebee_selinux policy. I think here could be the solution: http://linuxmanpages.net/manpages/fedora21/man8/bumblebee_selinux.8.html, customizing bumblebee_selinux policy correctly.

**Comment by gsgatlin** [comment] 2015-10-21 18:36
I recently did a install on fedora 21 and it was in "enforcing" mode and bumblebee worked fine with the selinux policy module I made.

Can you try setting it to enforcing and try to run something? Like 

optirun -b primus glxgears

And when it fails, post the

/var/log/audit/audit.log

 to a site like pastebin.com or fpaste.com? And post the link here. Are you using workstation or are you using some other spin? If a spin, which one are you using? (I think I only tested it with MATE...)

**Comment by elHippieCosmico** [comment] 2015-10-22 17:27
Yes, of course... I already tried returning to enforcing mode, and the same error appears again:

*$ optirun glxgears
Xlib: extension "GLX" missing on display ":8".
Error: couldn't get an RGB, Double-buffered visual*

*$ optirun glxspheres
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
Xlib:  extension "GLX" missing on display ":8".
ERROR in line 630:
Could not obtain RGB visual with requested properties*

*$ optirun -b primus glxgears
[ 3557.499286] [ERROR]Accel/display bridge primus is not installed.*

In my case, I was using Fedora 20 Workstation, with Bumblebee working OK. The problem appeared when I upgraded to Fedora 21 (it was something about selinux, but I don't remember exactly. I think it may have been the bumblebee-selinux policy).

**Comment by gsgatlin** [comment] 2015-10-22 17:38
Ok. Well, if you do a http://pastebin.com/ or http://www.fpaste.org/ of your /var/log/audit/audit.log perhaps I can use audit2allow to find out why its failing for you.

**Comment by gsgatlin** [comment] 2015-10-22 17:43
Also, if I can find out why its failing for you I can add those line to the /usr/share/selinux/devel/bumblebee-nvidia.te module to fix it.

**Comment by elHippieCosmico** [comment] 2015-10-25 13:47
Sorry for the delay. I'm trying to paste the entire audit.log file, but pastebin.com tells me that it's too big (2,2M), and fpaste.org doesn't return the paste ID. Do you need the complete file? or a summary is enough? (e.g. filtering the lines that contain 'bumblebee')

**Comment by gsgatlin** [comment] 2015-10-25 14:42
Hmnn. Ok. Yeah. Just the end of the file where you see mention of bumblebee should be good enough I would think.

**Comment by elHippieCosmico** [comment] 2015-10-25 18:10
I did
*$ grep bumblebee audit.log > audit_bumblebee.log*

Here is the file: http://pastebin.com/ZjKZ1dQj
 I hope it's useful...

**Comment by gsgatlin** [comment] 2015-10-26 19:19
Does running:

/usr/sbin/semodule -i /usr/share/selinux/devel/bumblebee-nvidia.pp

help?

Note, this should automagically be run on package upgrade but on my test f20-f21 fedup install it did not for some strange reason that makes no sense to me.

**Comment by elHippieCosmico** [comment] 2015-10-26 20:52
It's the same thing that happened when I upgrade with fedup...

*$ sudo /usr/sbin/semodule -i /usr/share/selinux/devel/bumblebee-nvidia.pp
libsepol.print_missing_requirements: mypol's global requirements were not met: type/attribute nx_exec_t (No such file or directory).
libsemanage.semanage_link_sandbox: Link packages failed (No such file or directory).
/usr/sbin/semodule:  Failed!*

**Comment by gsgatlin** [comment] 2015-10-26 21:04
Ok. I'm not a super expert at selinux or anything but I don't think the problem is caused by bumblebee-nvidia.pp or bumblebee-nvidia.te

[gsgatlin@t540p sources]$ grep nx_exec_t bumblebee-nvidia.te
[gsgatlin@t540p sources]$ 

In the output it mentions "mypol's global requirements were not met"

What happens if you run:

semodule -r mypol

or

semodule -r mypol.pp

(Not sure about the syntax)

and then re-run the command

/usr/sbin/semodule -i /usr/share/selinux/devel/bumblebee-nvidia.pp

Does that change anything? Did you make your own "mypol" module at some point in the past?

**Comment by elHippieCosmico** [comment] 2015-10-26 21:20
*$ sudo semodule -r mypol.pp
libsemanage.get_module_file_by_name: Module mypol.pp was not found.
semodule:  Failed on mypol.pp!
$ sudo semodule -r mypol
libsemanage.get_module_file_by_name: Module mypol was not found.
semodule:  Failed on mypol!*

No, I didn't make my own "mypol" neither I changed something about SELinux.

**Comment by elHippieCosmico** [comment] 2015-10-26 21:25
Oh! now I do *sudo /usr/sbin/semodule -i /usr/share/selinux/devel/bumblebee-nvidia.pp* and don't returns anything... and *optirun glxspheres* works!

I'll do a reboot and I'll see if it's still working...

**Comment by elHippieCosmico** [comment] 2015-10-26 22:06
Yes, optirun works after reboot; and /proc/acpi/bbswitch change ON and OFF correctly.
I wish I understood what help, to replicate if it fails again later... :P

**Comment by gsgatlin** [comment] 2015-10-26 22:12
It seems to work ok if I fedup from fresh install of fedora 21 to fedora 22. I am unsure what was wrong on your system. Sorry about that. I think maybe there was something weird going on with the fedup process from fedora 20 to fedora 21.

The only problem I am having after fedup from fedora 21 to fedora 22 is there is a entry in grub that says:

Fedora (fedup) 22 (Twenty Two)

That is the default that I am usure how to get rid of. I will try to investigate that further tomorrow. Sorry I could not be more help with the understanding part.

**Comment by elHippieCosmico** [comment] 2015-10-26 22:28
It was helpful! thanks a lot!
