### ISSUE TITLE
Laptop hangs upon trying to launch X with bumblebee running (not related to current powersaving issue)

### ISSUE THREAD

**Issue by bi0shacker001** [Bumblebee-Project/Bumblebee#809] opened 2016-10-03 16:59 UTC
Tested on: Archlinux, Ubuntu 16.04, Opensuse Tumbleweed, and Archlinux (again)
Bumblebee works fine when starting it after the system boots up. Setting it to start at boot causes the entire system to hang (kernel hard lock, not just graphics.)
Uses bbswitch for powersaving, and proprietary NVidia drivers. booting with acpi_osi=! acpi_osi="Windows 2009" as workaround has no effect, as does turning on the Nvidia card with bbswitch prior to launching X.
system: MSI gl62-6qf
i7-6700HQ
12GB DDR4
NVidia GTX 960m graphics
3 drives (128GB generic M2 SSD, 2TB Seagate M007 Hard drive, and 500GB Evo 850 SSD)

**Comment by Lekensteyn** [comment] 2016-10-03 18:18
Duplicate of #808

**Closed by Lekensteyn** 2016-10-03 18:18 UTC
