### ISSUE TITLE
Low perfomance on nvidia video card but good on intel

### ISSUE THREAD

**Issue by Canibus** [Bumblebee-Project/Bumblebee#741] opened 2016-02-26 07:28 UTC
Hi guys. Here what i have:
-kernel 4.2.0
-hardware( NVIDIA 740M and Intel 4200 or 4400 ( i forgor ))
-NVIDIA drivers 361 
-optirun bumblebee 3.2.1
-Ubuntu 14.04
So, lets see to problem. Here is some test that proof perfomance of different video cards
![2016-02-26 08 59 56](https://cloud.githubusercontent.com/assets/9164050/13345859/f6d80eda-dc6a-11e5-987c-ed0c9c394248.png)
I cant understand why intel video card is more better than nvidia. Please help me

**Comment by karolherbst** [comment] 2016-02-26 22:56
because of the PCIe bottleneck. Try a benchmark.

**Comment by Canibus** [comment] 2016-02-26 22:59
karolherbst which one?

**Comment by karolherbst** [comment] 2016-02-26 23:02
unigine heaven is a good one

**Comment by ArchangeGabriel** [comment] 2016-05-06 14:41
I’m closing this as a dupe of https://github.com/amonakov/primus/issues/176. I will open an issue about adding some documentation on PCIe bottleneck and how to check this.

**Closed by ArchangeGabriel** 2016-05-06 14:41 UTC
